name: Dependabot CI Trigger
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-existing-ci:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/pytest.yml # Path to your existing CI file
    secrets: inherit # This passes secrets to the called workflow
