name: Dependabot CI Trigger
on:
  pull_request:

jobs:
  call-existing-ci:
    if: ${{ github.actor == 'dependabot[bot]' }}
    secrets: inherit # This passes secrets to the called workflow
    steps:
      - uses: ./.github/workflows/pytest.yml # Path to your existing CI file
