name: Dependabot CI Trigger
on:
  pull_request:

jobs:
  call-workflow-pytest:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/pytest.yml@main # Path to your existing CI file
    secrets: inherit # This passes secrets to the called workflow
